"""numeric consistency for quantity columns

Revision ID: 2208c8e60855
Revises: 8df5b1f79497
Create Date: 2026-09-22 10:23:28.708111

El negocio vende medios cartones de huevos, asi que `products.min_stock` y
`purchase_items.quantity` no pueden quedarse en `Integer`: son las dos unicas
columnas de cantidad del schema que todavia no son `Numeric(10, 4)`, mientras
que sus vecinas inmediatas (`products.stock`, `purchase_items.remaining_quantity`)
ya lo son.

Correccion manual sobre el autogenerate:
  * Se anadio `postgresql_using` a los dos `op.alter_column` del upgrade
    (`"min_stock::numeric(10,4)"` y `"quantity::numeric(10,4)"`). El
    autogenerate no lo emite, y sin el, Postgres rechaza el cast implicito
    integer -> numeric con
    'column "min_stock" cannot be cast automatically to type numeric'
    (o hace algo distinto de lo que se pide, segun la version). Con el cast
    explicito los valores enteros existentes se preservan tal cual, solo
    cambia la representacion (100 -> 100.0000).
  * Se anadio `postgresql_using` tambien a los dos `op.alter_column` del
    downgrade (`"min_stock::integer"` y `"quantity::integer"`), por el mismo
    motivo: sin el, el ALTER TABLE de vuelta a INTEGER falla igual.

    ADVERTENCIA - el downgrade PIERDE DATOS: si entre el upgrade y el
    downgrade se registro alguna cantidad fraccionaria (p.ej. medio carton),
    el cast numeric->integer de Postgres la redondea al entero mas cercano
    (con .5 redondeando hacia afuera de cero: 12.5 -> 13, -12.5 -> -13; no es
    un truncado hacia cero ni redondeo bancario) y la fraccion original no se
    recupera. Verificado en la practica: ver el comando de verificacion en el
    reporte de la Task 8. Esto no es reversible. Antes de bajar esta revision
    en un ambiente con datos reales hay que decidir conscientemente si esa
    perdida es aceptable.

El resto del autogenerate salio correcto y se dejo tal cual: no cualifico el
schema en ninguna operacion (se resuelve por el search_path de env.py), y no
toco ninguna otra columna ni tabla.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2208c8e60855'
down_revision: Union[str, None] = '8df5b1f79497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'min_stock',
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
        postgresql_using="min_stock::numeric(10,4)",
    )
    op.alter_column(
        'purchase_items', 'quantity',
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
        postgresql_using="quantity::numeric(10,4)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ADVERTENCIA: este downgrade PIERDE DATOS. Cualquier cantidad fraccionaria
    # registrada mientras la columna fue Numeric(10,4) se redondea al volver a
    # Integer (Postgres redondea el cast numeric->integer al entero mas
    # cercano, p.ej. 12.5 -> 13) y ese decimal no se recupera. Ver el
    # docstring de arriba.
    op.alter_column(
        'purchase_items', 'quantity',
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="quantity::integer",
    )
    op.alter_column(
        'products', 'min_stock',
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="min_stock::integer",
    )
    # ### end Alembic commands ###
