"""cash movements occurred at

Revision ID: 2be582e95e0a
Revises: 9bd1cde470ea
Create Date: 2026-09-23 16:21:29.387142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be582e95e0a'
down_revision: Union[str, None] = '9bd1cde470ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_movements', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index('ix_cash_movements_movement_date', table_name='cash_movements')
    op.create_index(op.f('ix_cash_movements_occurred_at'), 'cash_movements', ['occurred_at'], unique=False)
    op.drop_column('cash_movements', 'movement_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_movements', sa.Column('movement_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cash_movements_occurred_at'), table_name='cash_movements')
    op.create_index('ix_cash_movements_movement_date', 'cash_movements', ['movement_date'], unique=False)
    op.drop_column('cash_movements', 'occurred_at')
    # ### end Alembic commands ###
