"""initial schema

Revision ID: 7c8a87a5384a
Revises: 
Create Date: 2026-09-21 21:35:02.455870

Reproduce el esquema que hoy existe en db_dev, incluidos los parches que
aplicaba ensure_schema_compatibility() en caliente (purchase_items.remaining_quantity,
sale_items.discount_percent / discount_amount, sales.is_payment_pending y los
Numeric(10, 4) de las cantidades).

Correcciones manuales sobre el autogenerate (ver task-4-report.md):
  * Se borro el `op.drop_table('alembic_version')` del upgrade y el
    `op.create_table('alembic_version', ...)` del downgrade.  Eran un artefacto
    de env.py, que pasaba el nombre real del schema destino como
    version_table_schema mientras reflejaba el schema por defecto de la
    conexion, de modo que el autogenerate no reconocia su propia tabla de
    version y proponia borrarla.  La causa raiz ya esta arreglada en env.py,
    que ahora pasa None como version_table_schema.
  * Se anadio el DROP TYPE de earning_mode_enum al downgrade: op.create_table
    emite el CREATE TYPE (before_create con checkfirst=False) pero op.drop_table
    no emite el DROP, y sin el un downgrade + upgrade fallaria con
    "type earning_mode_enum already exists".
  * Se anadio server_default=sa.text('0') a purchase_items.remaining_quantity
    para reproducir el DEFAULT 0 que ensure_schema_compatibility() dejo en
    produccion.  La columna es NOT NULL: sin ese default, un INSERT que la
    omita funciona en db_dev y fallaria aqui.

Ninguna operacion cualifica el schema explicitamente: el destino se resuelve por
el search_path que fija env.py, de modo que esta misma revision sirve para
db_dev, db_v2 o un schema de test.  Lo vigila
test_migration_emits_no_hardcoded_schema, que rechaza cualquier revision donde
aparezca ese parametro; por eso esta nota lo describe en prosa en vez de
escribirlo literal.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8a87a5384a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('earning_mode', sa.Enum('percent', 'fee', name='earning_mode_enum'), server_default=sa.text("'percent'"), nullable=False),
    sa.Column('earning_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earning_fee_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('customer_product_cycles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('avg_interval_days', sa.Integer(), nullable=True),
    sa.Column('estimated_next_purchase', sa.Date(), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=False),
    sa.Column('last_quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_product_cycles_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_customer_product_cycles_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_product_cycles')),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_customer_product')
    )
    op.create_index(op.f('ix_customer_product_cycles_customer_id'), 'customer_product_cycles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_product_cycles_product_id'), 'customer_product_cycles', ['product_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_index(op.f('ix_purchases_reference_number'), 'purchases', ['reference_number'], unique=True)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_payment_pending', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_user_id'), 'sales', ['user_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_purchase_items_purchase_id_purchases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_items'))
    )
    op.create_index(op.f('ix_purchase_items_product_id'), 'purchase_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_profit_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_profit_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_price_overridden', sa.Boolean(), nullable=False),
    sa.Column('pricing_exception_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_items_sale_id_sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_items'))
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_table('sale_item_lot_allocations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_item_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lot_purchase_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], name=op.f('fk_sale_item_lot_allocations_purchase_item_id_purchase_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], name=op.f('fk_sale_item_lot_allocations_sale_item_id_sale_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_item_lot_allocations'))
    )
    op.create_index(op.f('ix_sale_item_lot_allocations_purchase_item_id'), 'sale_item_lot_allocations', ['purchase_item_id'], unique=False)
    op.create_index(op.f('ix_sale_item_lot_allocations_sale_item_id'), 'sale_item_lot_allocations', ['sale_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_item_lot_allocations_sale_item_id'), table_name='sale_item_lot_allocations')
    op.drop_index(op.f('ix_sale_item_lot_allocations_purchase_item_id'), table_name='sale_item_lot_allocations')
    op.drop_table('sale_item_lot_allocations')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_product_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_sales_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_reference_number'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_customer_product_cycles_product_id'), table_name='customer_product_cycles')
    op.drop_index(op.f('ix_customer_product_cycles_customer_id'), table_name='customer_product_cycles')
    op.drop_table('customer_product_cycles')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
    # op.create_table('products', ...) emitio el CREATE TYPE del enum nativo;
    # op.drop_table no emite el DROP TYPE, asi que hay que hacerlo a mano o un
    # upgrade posterior fallaria con "type earning_mode_enum already exists".
    sa.Enum(name="earning_mode_enum").drop(op.get_bind(), checkfirst=False)
