"""add payment fields and cash movements

Revision ID: 8df5b1f79497
Revises: 7c8a87a5384a
Create Date: 2026-09-22 10:12:48.060180

Los siete campos nuevos salen del diff contra la hoja de calculo de Revenew, y
`cash_movements` es el libro de caja que hoy vive en una pestania de esa hoja.

Las siete columnas se anaden como NULLABLE a proposito: las cuatro tablas
destino ya tienen datos en produccion, asi que un NOT NULL sin default haria
fallar el ALTER TABLE.  En particular sales.payment_date se queda nullable y
SIN CHECK contra sales.date: en los registros reales hay una venta marcada como
pagada sin fecha de pago, y otra cuya fecha de pago es anterior a la venta.
Cualquier invariante que parezca obvia aqui ya esta violada por los datos.

`cash_movements` nace VACIA: importar la pestania del Sheet esta fuera del
alcance de esta revision, y por eso la tabla tampoco entra en el TABLE_ORDER de
scripts/copy_schema_data.py.  El saldo acumulado no se guarda como columna: se
calcula al leer con SUM(...) OVER (ORDER BY movement_date).  Guardarlo fue la
fuente de desincronizacion en la hoja de la que viene este modelo.

Correccion manual sobre el autogenerate:
  * Se anadio el DROP TYPE de cash_movement_type_enum al final del downgrade.
    Es el segundo enum nativo del proyecto y repite exactamente el fallo del
    primero (earning_mode_enum en la revision 001): op.create_table emite el
    CREATE TYPE del enum (before_create con checkfirst=False) pero op.drop_table
    NO emite el DROP TYPE correspondiente.  Sin esta linea, el tipo sobrevive al
    downgrade y el siguiente upgrade falla con
    'type "cash_movement_type_enum" already exists'.  Verificado: antes de
    anadirla, test_upgrade_downgrade_upgrade_round_trip fallaba reportando
    [('cash_movement_type_enum',)] como tipo huerfano.

El resto del autogenerate salio correcto y se dejo tal cual: no cualifico el
schema en ninguna operacion, no duplico ni desplazo el CREATE TYPE, conservo el
server_default gen_random_uuid() de la PK y nombro los indices y constraints via
op.f() siguiendo la naming convention de Base.metadata
(ix_cash_movements_sale_id, ix_cash_movements_purchase_id,
ix_cash_movements_movement_date, pk_cash_movements y los dos fk_*).

Como en la revision 001, ninguna operacion cualifica el schema destino: se
resuelve por el search_path que fija env.py, de modo que esta revision sirve
igual para db_dev, db_v2 o un schema de test.  Lo vigila
test_migration_emits_no_hardcoded_schema, que rechaza cualquier revision donde
aparezca ese parametro; por eso esta nota lo describe en prosa.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df5b1f79497'
down_revision: Union[str, None] = '7c8a87a5384a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_movements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('entrada', 'salida', 'aporte_socio', 'retiro_socio', name='cash_movement_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_cash_movements_purchase_id_purchases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_cash_movements_sale_id_sales'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_movements'))
    )
    op.create_index(op.f('ix_cash_movements_movement_date'), 'cash_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_cash_movements_purchase_id'), 'cash_movements', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_sale_id'), 'cash_movements', ['sale_id'], unique=False)
    op.add_column('customer_product_cycles', sa.Column('projection_method', sa.String(length=20), nullable=True))
    op.add_column('customer_product_cycles', sa.Column('projection_confidence', sa.String(length=20), nullable=True))
    op.add_column('customer_product_cycles', sa.Column('calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('purchases', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('sale_items', sa.Column('expected_unit_margin', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('sales', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'payment_date')
    op.drop_column('sale_items', 'expected_unit_margin')
    op.drop_column('purchases', 'payment_method')
    op.drop_column('customer_product_cycles', 'calendar_event_id')
    op.drop_column('customer_product_cycles', 'projection_confidence')
    op.drop_column('customer_product_cycles', 'projection_method')
    op.drop_index(op.f('ix_cash_movements_sale_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_purchase_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_movement_date'), table_name='cash_movements')
    op.drop_table('cash_movements')
    # ### end Alembic commands ###
    # op.create_table('cash_movements', ...) emitio el CREATE TYPE del enum
    # nativo; op.drop_table no emite el DROP TYPE, asi que hay que hacerlo a
    # mano o un upgrade posterior fallaria con
    # "type cash_movement_type_enum already exists".  Mismo patron que
    # earning_mode_enum en la revision 001.
    sa.Enum(name="cash_movement_type_enum").drop(op.get_bind(), checkfirst=False)
