"""occurred at instants

Revision ID: a21d7bd9293c
Revises: d77ada8b6513
Create Date: 2026-09-23 21:50:34.562600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21d7bd9293c'
down_revision: Union[str, None] = 'd77ada8b6513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'occurred_at')
    op.drop_column('purchases', 'occurred_at')
    # ### end Alembic commands ###
