"""numeric avg interval days

Revision ID: d77ada8b6513
Revises: 2be582e95e0a
Create Date: 2026-09-23 17:00:21.162140

`customer_product_cycles.avg_interval_days` deja de ser un `Integer`: la
proyeccion ahora usa EWMA (media movil exponencialmente ponderada) en vez de
la media simple, y el resultado de esa cuenta rara vez es un entero — Cecy
proyecta a 19.3318 dias, no 19. Redondear a entero en cada actualizacion tira
precision que despues se necesita (una diferencia de 0.3 dias por ciclo, tras
docenas de recalculos, termina corriendo la fecha proyectada varios dias).

Correccion manual sobre el autogenerate:
  * Se anadio `postgresql_using="avg_interval_days::numeric(10,4)"` al
    `op.alter_column` del upgrade. El autogenerate no lo emite, y sin el,
    Postgres rechaza el cast implicito integer -> numeric con
    'column "avg_interval_days" cannot be cast automatically to type numeric'.
    Con el cast explicito los valores enteros existentes se preservan tal
    cual, solo cambia la representacion (30 -> 30.0000).
  * Se anadio `postgresql_using="avg_interval_days::integer"` tambien al
    `op.alter_column` del downgrade, por el mismo motivo: sin el, el ALTER
    TABLE de vuelta a INTEGER falla igual.

    ADVERTENCIA - el downgrade PIERDE DATOS: cualquier intervalo fraccionario
    calculado por EWMA mientras la columna fue Numeric(10,4) se redondea al
    entero mas cercano al volver a INTEGER (Postgres redondea el cast
    numeric->integer, con .5 redondeando hacia afuera de cero: 19.5 -> 20,
    -19.5 -> -20; no es un truncado hacia cero ni redondeo bancario) y la
    fraccion original no se recupera. Antes de bajar esta revision en un
    ambiente con datos reales hay que decidir conscientemente si esa perdida
    es aceptable.

El resto del autogenerate salio correcto y se dejo tal cual: no cualifico el
schema en ninguna operacion (se resuelve por el search_path de env.py), y no
toco ninguna otra columna ni tabla.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77ada8b6513'
down_revision: Union[str, None] = '2be582e95e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'customer_product_cycles', 'avg_interval_days',
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=True,
        postgresql_using="avg_interval_days::numeric(10,4)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ADVERTENCIA: este downgrade PIERDE DATOS. Cualquier intervalo
    # fraccionario calculado por EWMA mientras la columna fue Numeric(10,4)
    # se redondea al entero mas cercano al volver a INTEGER (Postgres
    # redondea el cast numeric->integer al entero mas cercano, p.ej.
    # 19.3318 -> 19) y ese decimal no se recupera. Ver el docstring de arriba.
    op.alter_column(
        'customer_product_cycles', 'avg_interval_days',
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using="avg_interval_days::integer",
    )
    # ### end Alembic commands ###
